In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.8.0


In [17]:
hello = tf.constant('Hello')
world = tf.constant('World')

In [18]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [19]:
with tf.Session() as sess:
    result = sess.run(hello+" "+ world)

In [20]:
result

b'Hello World'

In [25]:
a = tf.constant(10)
b = tf.constant(20)

a+b

<tf.Tensor 'add_8:0' shape=() dtype=int32>

In [27]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [28]:
result

30

In [29]:
const = tf.constant(10)
fill_mat = tf.fill((4,4),10)
myzeros = tf.zeros((4,4))
myones = tf.ones((4,4))
myrandn  = tf.random_normal((4,4),mean=0,stddev=0.1)
myrandu = tf.random_uniform((4,4),minval=0,maxval=10)


In [30]:
myops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [36]:
with tf.Session() as sess:
    for op in myops:
        result = sess.run(op)
        print(result)
        print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[-0.05254205  0.02179705 -0.05331737  0.03153193]
 [-0.03713079  0.03026357 -0.00627011  0.02706343]
 [-0.02622802 -0.18061224 -0.06984285 -0.03066736]
 [ 0.12116157  0.07286108  0.07054261 -0.17086172]]


[[ 0.77064037  4.49956656  1.22955561  6.10935926]
 [ 6.89431095  6.612257    4.86825943  2.96794057]
 [ 3.61388445  5.01381874  8.37511444  1.29029989]
 [ 1.2576437   2.48109579  5.35961151  2.24730611]]




In [37]:
a = tf.constant([
    [1,2],
    [3,4]
])
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [66]:
b = tf.constant(
    [[10],
    [20]]
)
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [67]:
my_result = tf.multiply(a,b)

In [68]:
sess = tf.InteractiveSession()

C:\Users\Vinit Jain\Anaconda3\lib\site-packages\tensorflow\python\client\session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [69]:
sess.run(my_result)

array([[10, 20],
       [60, 80]])

In [70]:
tf.Session(clear)

NameError: name 'clear' is not defined